import type { Metadata } from 'next'
import { Fragment_Mono, JetBrains_Mono, Press_Start_2P } from 'next/font/google'
import 'nextra-theme-docs/style.css'
import '@workspace/ui/globals.css'
import { Footer, Layout } from 'nextra-theme-docs'
import { getPageMap } from 'nextra/page-map'
import { Steps } from 'nextra/components'
import NavbarCompo from '@/components/layout/navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--next-font-jetbrains-mono',
  style: ['normal'],
  weight: ['400', '700'],
})
const pressStart2p = Press_Start_2P({
  subsets: ['greek', 'latin', 'cyrillic-ext', 'latin-ext', 'cyrillic'],
  variable: '--next-font-pressStart2p',
  style: ['normal'],
  weight: ['400'],
})

const fragmentMono = Fragment_Mono({
  subsets: ['latin'],
  variable: '--next-font-fragment-mono',
  weight: ['400'],
})

const footer = <Footer>MIT {new Date().getFullYear()} © Docsy</Footer>
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <body
        className={`${jetbrainsMono.variable} ${pressStart2p.variable} ${fragmentMono.variable} antialiased `}
      >
        <Layout
          navbar={NavbarCompo()}
          pageMap={await getPageMap()}
          docsRepositoryBase="https://github.com/GaureshArt/docsy/tree/main/apps/docs"
          footer={footer}
        >
          <Steps />
          {children}
        </Layout>
      </body>
    </html>
  )
}
